### ISSUE TITLE
Add Nginx Reverse Proxy to Simplify Port Exposure

### ISSUE THREAD

**Issue by JohannLai** [rag-web-ui/rag-web-ui#47]
## Background
Currently, the Docker Compose configuration exposes multiple ports (3000 for frontend, 8000 for backend, etc.). This creates unnecessary exposure and complicates the deployment. Adding Nginx as a reverse proxy would allow us to expose only a single port while properly routing all traffic internally.

## Proposed Changes
Add Nginx service to handle all incoming traffic through a single port (80/443), which will:
1. Provide a single entry point for all services
2. Handle routing between frontend and backend
3. Prepare for future SSL implementation
4. Improve security by reducing exposed ports

## Implementation Details
Add the following to docker-compose.yml:

```yaml:docker-compose.yml
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      # - "443:443"  # For future SSL implementation
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend
    networks:
      - app_network
```

Create `nginx/conf.d/default.conf`:

```nginx
server {
    listen 80;
    server_name localhost;

    # Frontend routing
    location / {
        proxy_pass http://frontend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Backend API routing
    location /api {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

Then remove the port mappings from frontend and backend services:
```yaml
services:
  frontend:
    # Remove ports section
    # ports:
    #   - "3000:3000"
    
  backend:
    # Remove ports section
    # ports:
    #   - "8000:8000"
```

## Benefits
1. **Simplified Port Management**: Only port 80 (and optionally 443 for HTTPS) needs to be exposed
2. **Enhanced Security**: Internal services are not directly exposed to the internet
3. **Centralized Control**: All traffic routing can be managed in one place
4. **Easy SSL Implementation**: When needed, SSL can be terminated at Nginx level

## Next Steps
1. Remove unnecessary port mappings from other services
2. Test the new configuration
3. Consider adding SSL configuration for production deployment
